[package]
name = "relay"
version = "0.1.0"
authors = ["haze"]
edition = "2018"

[dependencies]
crossbeam-utils = "0.6.5"
regex = "1.1.6"
lazy_static = "1.3.0"
failure = "0.1.5"


[dependencies.serenity]
path = "/Users/haze/workspace/serenity"
